CREATE DATABASE IF NOT EXISTS movietracker;

USE movietracker ;

CREATE TABLE IF NOT EXISTS User (
 email VARCHAR(255) NOT NULL,
 name VARCHAR(255) NOT NULL,
 password VARCHAR(255) NOT NULL,
 PRIMARY KEY (email)) IF NOT EXISTS;

CREATE TABLE IF NOT EXISTS Movie (
 movieID VARCHAR(255) NOT NULL,
 movieName VARCHAR(255) NOT NULL,
 description VARCHAR(255),
 posterImage VARCHAR(255),
 PRIMARY KEY (MovieID)) IF NOT EXISTS;

CREATE TABLE IF NOT EXISTS TVShow (
 seriesID VARCHAR(255) NOT NULL,
 seriesName VARCHAR(255) NOT NULL,
 description VARCHAR(255),
 posterImage VARCHAR(255),
 PRIMARY KEY (seriesID));